name = "DiscreteVoronoiDiagrams"
uuid = "74c5835c-25bd-4239-8bf4-447bc7683bfe"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.1"

[deps]
AsType = "ca91d8e0-3195-446d-9999-6c164cca1bdd"
EasyRanges = "bd0ea217-0861-4661-bed1-3e8ea598dd25"

[compat]
EasyRanges = "0.1.1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
