name = "DiscreteVoronoiDiagrams"
uuid = "74c5835c-25bd-4239-8bf4-447bc7683bfe"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.0"

[deps]
EasyRanges = "bd0ea217-0861-4661-bed1-3e8ea598dd25"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
